
SELECT
    YEAR_MONTH,
    CONSULT_REQUEST_COUNT,
    SUBSCRIPTION_COUNT,
    REGISTEND_COUNT,
    OPEN_COUNT,
    PAYEND_COUNT,
    SUBSCRIPTION_COUNT / NULLIF(CONSULT_REQUEST_COUNT, 0) AS CVR_1,
    REGISTEND_COUNT / NULLIF(SUBSCRIPTION_COUNT, 0) AS CVR_2,
    OPEN_COUNT / NULLIF(REGISTEND_COUNT, 0) AS CVR_3,
    PAYEND_COUNT / NULLIF(OPEN_COUNT, 0) AS CVR_4
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V03_CONTRACT_FUNNEL_CONVERSION
WHERE MAIN_CATEGORY_NAME = '렌탈'
    AND YEAR_MONTH <= '2026-03-01'
ORDER BY YEAR_MONTH;
