
SELECT
    RENTAL_MAIN_CATEGORY,
    RENTAL_SUB_CATEGORY,
    SUM(CONTRACT_COUNT) AS total_contract,
    SUM(OPEN_COUNT) AS total_open,
    SUM(PAYEND_COUNT) AS total_payend,
    ROUND(SUM(OPEN_COUNT) / NULLIF(SUM(CONTRACT_COUNT), 0) * 100, 2) AS open_cvr,
    ROUND(SUM(PAYEND_COUNT) / NULLIF(SUM(CONTRACT_COUNT), 0) * 100, 2) AS payend_cvr
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V06_RENTAL_CATEGORY_TRENDS
WHERE YEAR_MONTH <= '2026-03-01'
GROUP BY RENTAL_MAIN_CATEGORY, RENTAL_SUB_CATEGORY
ORDER BY open_cvr ASC;
