SELECT
    INSTALL_STATE,
    ROUND(SUM(OPEN_COUNT) / NULLIF(SUM(CONTRACT_COUNT), 0) * 100, 2) AS open_cvr,
    SUM(CONTRACT_COUNT) AS total_contract
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V06_RENTAL_CATEGORY_TRENDS
WHERE YEAR_MONTH <= '2026-03-01'
GROUP BY INSTALL_STATE
ORDER BY open_cvr ASC;