
SELECT
    RECEIVE_PATH_NAME,
    INFLOW_PATH_NAME,
    SUM(CONTRACT_COUNT) AS total_contract,
    SUM(OPEN_COUNT) AS total_open,
    SUM(PAYEND_COUNT) AS total_payend,
    ROUND(SUM(OPEN_COUNT) / NULLIF(SUM(CONTRACT_COUNT), 0) * 100, 2) AS open_cvr,
    ROUND(SUM(PAYEND_COUNT) / NULLIF(SUM(CONTRACT_COUNT), 0) * 100, 2) AS payend_cvr
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V04_CHANNEL_CONTRACT_PERFORMANCE
WHERE MAIN_CATEGORY_NAME = '렌탈'
    AND YEAR_MONTH <= '2026-03-01'
GROUP BY RECEIVE_PATH_NAME, INFLOW_PATH_NAME
ORDER BY open_cvr ASC;
