SELECT
    MAIN_CATEGORY_NAME,
    DIVISION_NAME,
    AVG(AVG_LEADTIME_DAYS) AS avg_lead,
    AVG(MEDIAN_LEADTIME_DAYS) AS median_lead,
    COUNT(*) AS row_cnt
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V11_CALL_TO_CONTRACT_CONVERSION
WHERE MAIN_CATEGORY_NAME = '렌탈'
GROUP BY MAIN_CATEGORY_NAME, DIVISION_NAME
ORDER BY DIVISION_NAME;